url: https://larsmathiesen.github.io
baseurl: /mihi/

# Site settings
title: Mihi
email: post@mihigames.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  #primary: 0d0c0c
  primary: fed136 # gul
  #primary: fed136 # gul
  #primary: CBE6D3
  secondary: fec503  
  #secondary: CBE6D3  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Åsta Lindemann
  pic: aasta.jpg
  position: Seniordesigner
  position2: Haltenbanken
  social:

- name: Åse Berge Haveland
  pic: aase.jpg
  position: Kvalitetsleder
  position2: Resipientanalyse AS
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/aasebh
    - title: envelope
      url: mailto:berge-haveland@hotmail.no

- name: Øyvind Setnes
  pic: oivind.jpg
  position: Senior forretningsutvikler
  position2: Tryg Forsikring
  social:
    - title: envelope
      url: mailto:oivind.setnes@tryg.no    

- name: Henning Klafstad
  pic: henning.png
  position: Seniorrådgiver
  position2: Nasjonalt senter for mat, helse og fysisk aktivitet
  social:
    - title: envelope
      url: mailto:henning.klafstad@hib.no
    - title: facebook
      url: https://www.facebook.com/Nasjonalt-senter-for-mat-helse-og-fysisk-aktivitet-120894154919278/

- name: Lars Mathiesen
  pic: lars.png
  position: Seniorkonsulent
  position2: Webstep AS
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/larsmathiesen
    - title: envelope
      url: mailto:lmathiesen@gmail.com


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty